/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import admin_screens.AdminMainScreen;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.dao.LogininfoDAO;
import model_to.LogininfoTO;
import user_screen.StudentMainScreen;
import utility.ErrorHandler;
import static utility.Operations.setApplicationIcon;
import utility.Validations;

/**
 *
 * @author HP
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
         setApplicationIcon(this);
        initComponents();
        setSize(650,480);
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnlogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfusername = new javax.swing.JTextField();
        jpfpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Password:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 158, 200, 24);

        jLabel2.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter UserName:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 65, 200, 24);

        jtfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfusername);
        jtfusername.setBounds(230, 65, 385, 30);

        jpfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpfpassword);
        jpfpassword.setBounds(230, 155, 387, 31);

        btnlogin.setBackground(new java.awt.Color(51, 51, 51));
        btnlogin.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        btnlogin.setText("Login..");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(180, 320, 308, 48);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/e.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 680, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
       String username=jtfusername.getText().trim();
       String password=new String(jpfpassword.getPassword());
       String message="";
       if(Validations.isEmpty(username) || Validations.isEmpty(password) ){
           message="please fill all the boxes";
       }else{
           LogininfoDAO action=new LogininfoDAO();
           LogininfoTO record= action.getRecord(username);
           if(record!=null){
               if(record.getPassword().equals(password)){
                   if(record.getRolename().equals("admin")){
                       AdminMainScreen ams=new AdminMainScreen();
                       ams.setVisible(true);
                       dispose();
                       if(record.getLastlogin()==null){
                           message=" welcome admin!! ";
                       }else{
                           message="your last visit:" + record.getLastlogin();
                       }
                       record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                       action.updateRecord(record);
                   }else if(record.getRolename().equals("student")){
                       StudentMainScreen sms=new StudentMainScreen(username);
                       sms.setVisible(true);
                       dispose();
                        if(record.getLastlogin()==null){
                           message=" welcome student!! ";
                       }else{
                           message="your last visit:" + record.getLastlogin();
                       }
                   }else{
                       message="insufficient privileges contact admin";
                   }
                   record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                       action.updateRecord(record);
               }else{
                   message="invalid username or password";
               }
           }else{
               message="invalid username or password";
           }
       }
      
      JOptionPane.showMessageDialog(this,message);
    }//GEN-LAST:event_btnloginActionPerformed

    private void jpfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfpasswordActionPerformed

    private void jtfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jpfpassword;
    private javax.swing.JTextField jtfusername;
    // End of variables declaration//GEN-END:variables
}
