
package screens;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.BookinfoDAO;
import model.dao.BranchinfoDAO;
import model.dao.StudentinfoDAO;
import model_to.BookinfoTO;
import model_to.BranchinfoTO;
import model_to.StudentinfoTO;
import utility.Operations;

public class ViewStudentinfo2 extends javax.swing.JInternalFrame {

    private List<StudentinfoTO> students;
     private JPopupMenu popup;
   private int selected_row;
   private List <StudentinfoTO> student;
   StudentinfoDAO action= new StudentinfoDAO();
   StudentinfoTO record=new StudentinfoTO();
    public ViewStudentinfo2() {
        initComponents();
        setSize(714,472);
        bindCombo(); 
        bindTableStudentinfo();
         
        selected_row=-1;
    }
       private void bindCombo()
       {
           student_combo1.removeAllItems();
           student_combo1.addItem("CHOOSE STUDENT");
           students=action.getAllRecord();
           
           for(StudentinfoTO st:students)
          {
            student_combo1.addItem(st);
           }
       }
        private void bindTableStudentinfo(){
            String[] col_names = {"Branch ID","Student ID","Student name","father name",
                     "contact no.","e-mail ID"};
            Object[][] records=null;
            int studentid=record.getStudentid();
            System.out.println(studentid);
            
             students=new StudentinfoDAO().getRecord(studentid);
           // students=new StudentinfoDAO().getAllRecord();
            if(students!=null && students.size()>0){
                records= new Object[students.size()][col_names.length];
                int index=0;
                for(StudentinfoTO st : students){
                    records[index]=new Object[]{st.getBranchid(),
                    st.getStudentid(),st.getStudentname(),st.getFathername()
                    ,st.getContactno(),st.getEmailid()};
                    index++;
                    }
                            
            }else{
                records= new Object[1][col_names.length];
                records[0]=new Object[]{"No Information Present","No Information Present",
                    "No Information Present","No Information Present","No Information Present",
                    "No Information Present"};
                
            }
            
            
            DefaultTableModel model=new DefaultTableModel(records,col_names);
            tbl_studentdetails.setModel(model);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_studentdetails = new javax.swing.JTable();
        student_combo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Student Details:");
        getContentPane().setLayout(null);

        tbl_studentdetails.setBackground(new java.awt.Color(153, 153, 153));
        tbl_studentdetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        tbl_studentdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_studentdetails);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 142, 680, 170);

        student_combo1.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        student_combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        student_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(student_combo1);
        student_combo1.setBounds(336, 66, 284, 28);

        jLabel1.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE STUDENT :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(68, 66, 219, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lll.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 739, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_combo1ActionPerformed
       
        if(student_combo1.getSelectedIndex()>0)
        {    
           record=(StudentinfoTO)student_combo1.getSelectedItem();
            bindTableStudentinfo();
        }   
        
    }//GEN-LAST:event_student_combo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<java.lang.Object> student_combo1;
    private javax.swing.JTable tbl_studentdetails;
    // End of variables declaration//GEN-END:variables
}
