/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_screen;

import admin_screens.ViewStudentinfo;
import javax.swing.ImageIcon;
import screens.ReturnBook;
import screens.ViewIssue;
import screens.ViewStudentinfo2;
import utility.ErrorHandler;
import static utility.Operations.openInternalFrame;
import static utility.Operations.setApplicationIcon;

/**
 *
 * @author HP
 */
public class StudentMainScreen extends javax.swing.JFrame {
    private String username1;

    public StudentMainScreen(String username) {
        this();
        username1 = username;
        setTitle(" welcome " +username1 + " !!!!! ");
    }
            
    /**
     * Creates new form StudentMainScreen
     */
    public StudentMainScreen() {
        setApplicationIcon(this);
        initComponents();
        setSize(1000,650);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        backgroundDesktopPane1 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane2 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane3 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane4 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane5 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane6 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane7 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane8 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane9 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane10 = new controls.BackgroundDesktopPane();
        backgroundDesktopPane11 = new controls.BackgroundDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        desktoppane = new controls.BackgroundDesktopPane();
        jMenuBar11 = new javax.swing.JMenuBar();
        jmi_studentinfo = new javax.swing.JMenu();
        jmi_viewInfo = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jmi_returnbook = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("jMenu11");

        jMenu12.setText("File");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar6.add(jMenu13);

        jMenu3.setText("File");
        jMenuBar7.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar7.add(jMenu4);

        jMenu14.setText("File");
        jMenuBar8.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar8.add(jMenu15);

        jMenu16.setText("File");
        jMenuBar9.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar9.add(jMenu17);

        jMenu18.setText("File");
        jMenuBar10.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar10.add(jMenu19);

        jMenu22.setText("jMenu22");

        jMenu23.setText("jMenu23");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(desktoppane, java.awt.BorderLayout.CENTER);

        jMenuBar11.setBackground(new java.awt.Color(255, 153, 0));

        jmi_studentinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/14.PNG"))); // NOI18N
        jmi_studentinfo.setText("Studentinfo");
        jmi_studentinfo.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N

        jmi_viewInfo.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jmi_viewInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jmi_viewInfo.setText("View Studentinfo");
        jmi_viewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_viewInfoActionPerformed(evt);
            }
        });
        jmi_studentinfo.add(jmi_viewInfo);

        jMenuBar11.add(jmi_studentinfo);

        jMenu20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/18.PNG"))); // NOI18N
        jMenu20.setText("Returninfo");
        jMenu20.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N

        jmi_returnbook.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jmi_returnbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16.PNG"))); // NOI18N
        jmi_returnbook.setText("ReturnBook");
        jmi_returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_returnbookActionPerformed(evt);
            }
        });
        jMenu20.add(jmi_returnbook);

        jMenuBar11.add(jMenu20);

        jMenu21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16.PNG"))); // NOI18N
        jMenu21.setText("IssueDetails");
        jMenu21.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jMenuItem1.setText("view issue details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem1);

        jMenuBar11.add(jMenu21);

        setJMenuBar(jMenuBar11);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_viewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_viewInfoActionPerformed
      openInternalFrame(desktoppane,new ViewStudentinfo2());
    }//GEN-LAST:event_jmi_viewInfoActionPerformed

    private void jmi_returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_returnbookActionPerformed
        openInternalFrame(desktoppane,new ReturnBook());
    }//GEN-LAST:event_jmi_returnbookActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openInternalFrame(desktoppane,new ViewIssue());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.BackgroundDesktopPane backgroundDesktopPane1;
    private controls.BackgroundDesktopPane backgroundDesktopPane10;
    private controls.BackgroundDesktopPane backgroundDesktopPane11;
    private controls.BackgroundDesktopPane backgroundDesktopPane2;
    private controls.BackgroundDesktopPane backgroundDesktopPane3;
    private controls.BackgroundDesktopPane backgroundDesktopPane4;
    private controls.BackgroundDesktopPane backgroundDesktopPane5;
    private controls.BackgroundDesktopPane backgroundDesktopPane6;
    private controls.BackgroundDesktopPane backgroundDesktopPane7;
    private controls.BackgroundDesktopPane backgroundDesktopPane8;
    private controls.BackgroundDesktopPane backgroundDesktopPane9;
    private controls.BackgroundDesktopPane desktoppane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmi_returnbook;
    private javax.swing.JMenu jmi_studentinfo;
    private javax.swing.JMenuItem jmi_viewInfo;
    // End of variables declaration//GEN-END:variables
}
