/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screens;

import javax.swing.JOptionPane;
import model.dao.BookinfoDAO;
import model.dao.LogininfoDAO;
import model_to.BookinfoTO;
import model_to.LogininfoTO;
import utility.Operations;
import utility.Validations;

/**
 *
 * @author HP
 */
public class AddBookinfo extends javax.swing.JInternalFrame {

    private boolean dot_present;

    /**
     * Creates new form AddBookinfo
     */
    public AddBookinfo() {
        initComponents();
        btnoperation.setText("Add book details");
    }

    public AddBookinfo(BookinfoTO record) {
        this();
        //  BookinfoTO record=new BookinfoTO();
        if (record != null) {
            itfbookid.setText(Integer.toString(record.getBookid()));
            jtfbookname.setText(record.getBookname());
            jtfauthorname.setText(record.getAuthorname());
            ftfprice.setText(Float.toString(record.getPrice()));
            itfedition.setText(Integer.toString(record.getEdition()));
            itfquantity.setText(Integer.toString(record.getQuantity()));
            btnoperation.setText("update book details");
            setTitle("update category details");

            itfbookid.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floatTextField1 = new controls.FloatTextField();
        floatTextField2 = new controls.FloatTextField();
        floatTextField3 = new controls.FloatTextField();
        floatTextField4 = new controls.FloatTextField();
        floatTextField5 = new controls.FloatTextField();
        floatTextField6 = new controls.FloatTextField();
        floatTextField7 = new controls.FloatTextField();
        floatTextField8 = new controls.FloatTextField();
        floatTextField9 = new controls.FloatTextField();
        floatTextField10 = new controls.FloatTextField();
        floatTextField11 = new controls.FloatTextField();
        intTextField1 = new controls.IntTextField();
        intTextField2 = new controls.IntTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfauthorname = new javax.swing.JTextField();
        jtfbookname = new javax.swing.JTextField();
        btnoperation = new javax.swing.JButton();
        ftfprice = new controls.FloatTextField();
        itfbookid = new controls.IntTextField();
        itfedition = new controls.IntTextField();
        itfquantity = new controls.IntTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Book Info");
        setPreferredSize(new java.awt.Dimension(638, 504));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Book Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 109, 160, 22);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter bookID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(45, 66, 130, 22);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Price:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(45, 195, 120, 22);

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Author Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(45, 151, 180, 22);

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Edition:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(45, 235, 140, 22);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Quantity:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(45, 286, 150, 22);

        jtfauthorname.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(jtfauthorname);
        jtfauthorname.setBounds(243, 145, 237, 28);

        jtfbookname.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jtfbookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbooknameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfbookname);
        jtfbookname.setBounds(243, 106, 237, 28);

        btnoperation.setBackground(new java.awt.Color(153, 153, 0));
        btnoperation.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnoperation.setText("Add Bookinfo");
        btnoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperationActionPerformed(evt);
            }
        });
        getContentPane().add(btnoperation);
        btnoperation.setBounds(103, 396, 331, 48);

        ftfprice.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        ftfprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfpriceActionPerformed(evt);
            }
        });
        getContentPane().add(ftfprice);
        ftfprice.setBounds(243, 191, 237, 25);

        itfbookid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(itfbookid);
        itfbookid.setBounds(243, 67, 237, 28);

        itfedition.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(itfedition);
        itfedition.setBounds(243, 235, 237, 28);

        itfquantity.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(itfquantity);
        itfquantity.setBounds(243, 281, 237, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/d.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 630, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfbooknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbooknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbooknameActionPerformed

    private void btnoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperationActionPerformed
        String message = "";
        boolean allvalid = true;
        String bookname = jtfbookname.getText().trim();
        String authorname = jtfauthorname.getText().trim();
        if (Validations.isEmpty(bookname) || Validations.isEmpty(authorname)) {
            message = "please fill all the boxes";
        }
        String price = ftfprice.getText().trim();
        if (Validations.isEmpty(price)) {
            message += "please enter some value in price";
            allvalid = false;
        } else if (Validations.isFloat(price)) {
            float p = Float.parseFloat(price);
            if (p == 0) {
                message += "please enter  value greater than zero";
                allvalid = false;
            }
        } else {
            message += "please enter number in price";
        }
        String bookid = itfbookid.getText().trim();
        String edition = itfedition.getText().trim();
        String quantity = itfquantity.getText().trim();
        if (Validations.isEmpty(bookid)) {
            message += "enter bookid";
            allvalid = false;
        }
        if (Validations.isEmpty(edition)) {
            message += "enter edition";
            allvalid = false;
        } else if (Validations.isInteger(edition)) {
            int e = Integer.parseInt(edition);
            if (e == 0) {
                message += "enter valid edition";
                allvalid = false;
            } else {
                message += "enter edition";
            }
        }
        if (Validations.isEmpty(quantity)) {
            message += "please enter some value in quantity";
            allvalid = false;
        } else if (Validations.isInteger(quantity)) {
            int q = Integer.parseInt(quantity);
            if (q <= 0) {
                message += "please enter  value greater than zero";
                allvalid = false;
            }
        } else {
            message += "please enter quantity";
        }
        if (allvalid) {
            BookinfoTO record = new BookinfoTO();
            record.setAuthorname(authorname);
            record.setBookname(bookname);
            record.setPrice(Float.parseFloat(price));
            record.setEdition(Integer.parseInt(edition));
            record.setBookid(Integer.parseInt(bookid));
            record.setQuantity(Integer.parseInt(quantity));
            BookinfoDAO action = new BookinfoDAO();
            if (btnoperation.getText().contains("Add")) {

                if (action.insertRecord(record)) {
                    message = "bookinfo is saved";
                } else {
                    message = "insertion failure" + action.getError_message();
                }
            } else if (btnoperation.getText().contains("update")) {
                if (action.updateRecord(record)) {
                    message = "bookinfo is updated";
                } else {
                    message = "updation failure" + action.getError_message();
                }
                ViewBookDetails vbi = new ViewBookDetails();
                Operations.openInternalFrame(getDesktopPane(), vbi);
                dispose();
            } else {
                message = "invalid operation ";
            }

        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnoperationActionPerformed

    private void ftfpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfpriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoperation;
    private controls.FloatTextField floatTextField1;
    private controls.FloatTextField floatTextField10;
    private controls.FloatTextField floatTextField11;
    private controls.FloatTextField floatTextField2;
    private controls.FloatTextField floatTextField3;
    private controls.FloatTextField floatTextField4;
    private controls.FloatTextField floatTextField5;
    private controls.FloatTextField floatTextField6;
    private controls.FloatTextField floatTextField7;
    private controls.FloatTextField floatTextField8;
    private controls.FloatTextField floatTextField9;
    private controls.FloatTextField ftfprice;
    private controls.IntTextField intTextField1;
    private controls.IntTextField intTextField2;
    private controls.IntTextField itfbookid;
    private controls.IntTextField itfedition;
    private controls.IntTextField itfquantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfauthorname;
    private javax.swing.JTextField jtfbookname;
    // End of variables declaration//GEN-END:variables
}
