/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screens;

import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.BookinfoDAO;
import model.dao.IssuedetailsDAO;
import model.dao.LogininfoDAO;
import model.dao.StudentinfoDAO;
import model_to.BookinfoTO;
import model_to.BranchinfoTO;
import model_to.IssuedetailsTO;
import model_to.LogininfoTO;
import model_to.StudentinfoTO;
import utility.ErrorHandler;
import utility.Validations;

/**
 *
 * @author HP
 */
public class AddIssueDetails extends javax.swing.JInternalFrame {

   private List<StudentinfoTO> students;
   //private List<IssuedetailsTO> student;
    private List<IssuedetailsTO> issues;
    private List<LogininfoTO> records;
    private List<BookinfoTO> bk;
     private JPopupMenu popup;
   private int selected_row;
   private List <IssuedetailsTO> issue;
   StudentinfoDAO action= new StudentinfoDAO();
   StudentinfoTO record=new StudentinfoTO();
   LogininfoDAO actions= new LogininfoDAO();
   LogininfoTO rec=new LogininfoTO();
   Date dt1;           
    public AddIssueDetails() {
        
        initComponents();
        bindStudentCombo();
        bindIssueCombo();
       // bindUserCombo();
       // bindTableIssuedetails();
    }
        
        private void bindStudentCombo(){
            students=new StudentinfoDAO().getAllRecord();
            jcbstudentid.removeAllItems();
            jcbstudentid.addItem("choose studentID");
            if(students!=null && students.size()>0){
               for(StudentinfoTO st : students){
                   jcbstudentid.addItem(st);
               } 
            }
        }
         private void bindIssueCombo(){
            bk=new BookinfoDAO().getAllRecord();
            jcbbookid.removeAllItems();
            jcbbookid.addItem("choose bookID");
            if(bk!=null && bk.size()>0){
               for(BookinfoTO bt : bk){
                   jcbbookid.addItem(bt);
               } 
            }
        }
        
         
             /* private void bindTableIssuedetails(){
            String[] col_names = {"Issue ID","Book ID","Issuedate","return date","noofdays",
                     "studentid","username"};
            Object[][] records=null;
            int bookid=record.getStudentid();
           System.out.println(bookid);
            
             IssuedetailsTO issue=new IssuedetailsDAO().getRecord(bookid);
            if(issues!=null && issues.size()>0){
                records= new Object[issues.size()][col_names.length];
                int index=0;
                for(IssuedetailsTO st : issues){
                    records[index]=new Object[]{st.getIssueid(),
                    st.getBookid(),st.getIssuedate(),st.getUsername(),st.getReturndate(),st.getNoofdays()
                    ,st.getStudentid()};
                    index++;
                    }
                            
            }else{
                records= new Object[1][col_names.length];
                records[0]=new Object[]{"No Information Present","No Information Present",
                    "No Information Present","No Information Present","No Information Present"
                        ,"No Information Present","No Information Present"
                   };
                
            }
            DefaultTableModel model=new DefaultTableModel(records,col_names);
            tableissue.setModel(model);
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblnoofdays = new javax.swing.JLabel();
        lblbookid = new javax.swing.JLabel();
        lblissuedate = new javax.swing.JLabel();
        jcbissuedate = new controls.CurrentDatePanel();
        itfnoofdays = new controls.IntTextField();
        lblstudentid = new javax.swing.JLabel();
        btnaddissuedetails = new javax.swing.JButton();
        jcbstudentid = new javax.swing.JComboBox<>();
        jcbbookid = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Issue Details");
        setPreferredSize(new java.awt.Dimension(638, 504));
        getContentPane().setLayout(null);

        lblnoofdays.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblnoofdays.setForeground(new java.awt.Color(255, 255, 255));
        lblnoofdays.setText("NoOfDays");
        getContentPane().add(lblnoofdays);
        lblnoofdays.setBounds(74, 252, 97, 26);

        lblbookid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblbookid.setForeground(new java.awt.Color(255, 255, 255));
        lblbookid.setText("BookID");
        getContentPane().add(lblbookid);
        lblbookid.setBounds(82, 72, 131, 26);

        lblissuedate.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblissuedate.setForeground(new java.awt.Color(255, 255, 255));
        lblissuedate.setText("IssueDate");
        getContentPane().add(lblissuedate);
        lblissuedate.setBounds(74, 159, 97, 26);

        jcbissuedate.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(jcbissuedate);
        jcbissuedate.setBounds(217, 157, 384, 28);

        itfnoofdays.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        itfnoofdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itfnoofdaysActionPerformed(evt);
            }
        });
        getContentPane().add(itfnoofdays);
        itfnoofdays.setBounds(217, 251, 384, 28);

        lblstudentid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblstudentid.setForeground(new java.awt.Color(255, 255, 255));
        lblstudentid.setText("StudentID");
        getContentPane().add(lblstudentid);
        lblstudentid.setBounds(74, 339, 97, 22);

        btnaddissuedetails.setBackground(new java.awt.Color(153, 153, 0));
        btnaddissuedetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnaddissuedetails.setText("Add Issue Details");
        btnaddissuedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddissuedetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddissuedetails);
        btnaddissuedetails.setBounds(231, 441, 318, 36);

        jcbstudentid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jcbstudentid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbstudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbstudentidActionPerformed(evt);
            }
        });
        getContentPane().add(jcbstudentid);
        jcbstudentid.setBounds(217, 336, 384, 28);

        jcbbookid.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jcbbookid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbookidActionPerformed(evt);
            }
        });
        getContentPane().add(jcbbookid);
        jcbbookid.setBounds(217, 69, 384, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/d.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddissuedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddissuedetailsActionPerformed
        String message="";
        boolean allvalid=true;
        
        
        if (jcbbookid.getSelectedIndex() == 0) {
            allvalid = false;
            message += "please choose any book\n\n";
        }
         String noofdays=itfnoofdays.getText().trim();
        if(Validations.isEmpty(noofdays)){
         message +="enter noofdays";
         allvalid=false;
     }
         if(jcbstudentid.getSelectedIndex()==0){
            allvalid=false;
            message +="please choose any student\n\n";
        }
         
        
         if(jcbissuedate.getSelectedDate()==null){
             message +="please choose any value\n\n";
             allvalid=false;
         }
         
         if(allvalid){
             IssuedetailsTO record=new IssuedetailsTO();
             StudentinfoTO st=(StudentinfoTO) jcbstudentid.getSelectedItem();
             BookinfoTO bt=(BookinfoTO) jcbbookid.getSelectedItem();
            // LogininfoTO bt=(LogininfoTO) jcbusername.getSelectedItem();
            Date dt=jcbissuedate.getSelectedDate();
             record.setIssuedate(dt);
            
             //record.setReturndate(jcbreturndate.getSelectedDate());
             //record.setIssueid(Integer.parseInt(issueid));
             record.setBookid(bt.getBookid());
             int days=Integer.parseInt(noofdays);
             record.setNoofdays(days);
             dt1=new Date(dt.getYear(),dt.getMonth(),dt.getDate()+days);
             record.setReturndate(dt1); 
             record.setStudentid(st.getStudentid());
            // record.setUsername(bt.getUsername());
             
             IssuedetailsDAO action=new IssuedetailsDAO();
             if(action.insertRecord(record)){
                 message +="issue details are added in system database";
             }else{
                 message ="insertion failure:" + action.getError_message();
             }
         }   
        if(allvalid){
        JOptionPane.showMessageDialog(this,message);
        }else{
            JOptionPane.showMessageDialog(this, message,"failure in working",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnaddissuedetailsActionPerformed

    private void jcbstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbstudentidActionPerformed
      
    }//GEN-LAST:event_jcbstudentidActionPerformed

    private void itfnoofdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itfnoofdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itfnoofdaysActionPerformed

    private void jcbbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbookidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddissuedetails;
    private controls.IntTextField itfnoofdays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<java.lang.Object> jcbbookid;
    private controls.CurrentDatePanel jcbissuedate;
    private javax.swing.JComboBox<java.lang.Object> jcbstudentid;
    private javax.swing.JLabel lblbookid;
    private javax.swing.JLabel lblissuedate;
    private javax.swing.JLabel lblnoofdays;
    private javax.swing.JLabel lblstudentid;
    // End of variables declaration//GEN-END:variables
}
