/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screens;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.BranchinfoDAO;
import model.dao.StudentinfoDAO;
import model_to.BranchinfoTO;
import model_to.StudentinfoTO;
import utility.Validations;

/**
 *
 * @author HP
 */
public class AddStudentInfo extends javax.swing.JInternalFrame {

    private List<BranchinfoTO> branches;

    public AddStudentInfo() {
        initComponents();
        bindBranchinfoCombo();
    }

    public AddStudentInfo(StudentinfoTO record) {
        this();
        if (record != null) {
            itfstudentid.setText(Integer.toString(record.getStudentid()));
            // itfstudentid.setText(record.getStudentid());
            jtfstudentname.setText(record.getStudentname());
            jtffathername.setText(record.getFathername());
            itfcontactno.setText(record.getContactno());
            jtfemailid.setText(record.getEmailid());
            String branchid = String.valueOf(jcbbranchid);
            
            
            btnoperation.setText("update book details");
            setTitle("update category details");
            itfstudentid.setVisible(true);
            itfstudentid.setEditable(false);
        }
    }

    private void bindBranchinfoCombo() {
        branches = new BranchinfoDAO().getAllRecord();
        jcbbranchid.removeAllItems();
        jcbbranchid.addItem("choose any branch");
        if (branches != null && branches.size() > 0) {
            for (BranchinfoTO bt : branches) {
                jcbbranchid.addItem(bt);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmi_contactno = new javax.swing.JLabel();
        jtffathername = new javax.swing.JTextField();
        jmi_studentid = new javax.swing.JLabel();
        jmi_studentname = new javax.swing.JLabel();
        jtfstudentname = new javax.swing.JTextField();
        jmi_fathername = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmi_emailid = new javax.swing.JLabel();
        jtfemailid = new javax.swing.JTextField();
        jcbbranchid = new javax.swing.JComboBox<>();
        btnoperation = new javax.swing.JButton();
        itfcontactno = new controls.IntTextField();
        itfstudentid = new controls.IntTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("add new studentinfo");
        setPreferredSize(new java.awt.Dimension(638, 504));
        getContentPane().setLayout(null);

        jmi_contactno.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_contactno.setForeground(new java.awt.Color(255, 255, 255));
        jmi_contactno.setText("contact no:");
        getContentPane().add(jmi_contactno);
        jmi_contactno.setBounds(177, 216, 120, 26);

        jtffathername.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(jtffathername);
        jtffathername.setBounds(301, 163, 273, 28);

        jmi_studentid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_studentid.setForeground(new java.awt.Color(255, 255, 255));
        jmi_studentid.setText("student id:");
        getContentPane().add(jmi_studentid);
        jmi_studentid.setBounds(177, 56, 110, 26);

        jmi_studentname.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_studentname.setForeground(new java.awt.Color(255, 255, 255));
        jmi_studentname.setText("student name:");
        getContentPane().add(jmi_studentname);
        jmi_studentname.setBounds(158, 110, 139, 26);

        jtfstudentname.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(jtfstudentname);
        jtfstudentname.setBounds(301, 109, 273, 28);

        jmi_fathername.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_fathername.setForeground(new java.awt.Color(255, 255, 255));
        jmi_fathername.setText("father name:");
        getContentPane().add(jmi_fathername);
        jmi_fathername.setBounds(177, 164, 120, 26);

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("branch id:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(177, 310, 108, 26);

        jmi_emailid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_emailid.setForeground(new java.awt.Color(255, 255, 255));
        jmi_emailid.setText("e-mail id:");
        getContentPane().add(jmi_emailid);
        jmi_emailid.setBounds(177, 264, 108, 26);

        jtfemailid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(jtfemailid);
        jtfemailid.setBounds(301, 263, 273, 28);

        jcbbranchid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jcbbranchid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbranchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbranchidActionPerformed(evt);
            }
        });
        getContentPane().add(jcbbranchid);
        jcbbranchid.setBounds(301, 309, 273, 28);

        btnoperation.setBackground(new java.awt.Color(153, 153, 0));
        btnoperation.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnoperation.setText("add studentinfo");
        btnoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperationActionPerformed(evt);
            }
        });
        getContentPane().add(btnoperation);
        btnoperation.setBounds(190, 380, 205, 39);

        itfcontactno.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(itfcontactno);
        itfcontactno.setBounds(301, 215, 273, 28);

        itfstudentid.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        getContentPane().add(itfstudentid);
        itfstudentid.setBounds(297, 56, 277, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/d.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 680, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperationActionPerformed
        String message = "";
        boolean allvalid = true;
        if (jcbbranchid.getSelectedIndex() == 0) {
            allvalid = false;
            message += "please choose any branch\n\n";
        }
        String studentname = jtfstudentname.getText().trim();
        if (Validations.isEmpty(studentname)) {
            allvalid = false;
            message += "please enter any student name\n\n";
        } else if (!Validations.onlyLetterAndSpace(studentname)) {
            allvalid = false;
            message += "student name only accept letter and spaces\n\n";
        }
        String fathername = jtffathername.getText().trim();
        if (Validations.isEmpty(fathername)) {
            allvalid = false;
            message += "please enter father name\n\n";
        } else if (!Validations.onlyLetterAndSpace(fathername)) {
            allvalid = false;
            message += "fathers name only accept letter and spaces\n\n";
        }
        String contactno = itfcontactno.getText().trim();
        if (Validations.isEmpty(contactno)) {
            message += "enter contact number";
            allvalid = false;
        }
        String studentid = itfstudentid.getText().trim();
        if (Validations.isEmpty(studentid)) {
            message += "enter studentid";
            allvalid = false;
        }
        String emailid = jtfemailid.getText().trim();
        if (Validations.isEmpty(emailid)) {
            message += "enter emailid";
            allvalid = false;
        }
        if (allvalid) {
            StudentinfoTO record = new StudentinfoTO();
            BranchinfoTO bt = (BranchinfoTO) jcbbranchid.getSelectedItem();
            record.setStudentname(studentname);
            record.setFathername(fathername);
            record.setEmailid(emailid);
            record.setContactno(contactno);
            record.setBranchid(bt.getBranchid());
            record.setStudentid(Integer.parseInt(studentid));
            StudentinfoDAO action = new StudentinfoDAO();
            if (action.insertRecord(record)) {
                message += "new student info is added in system database";
            } else {
                message = "insertion failure:" + action.getError_message();
            }
        }

        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnoperationActionPerformed

    private void jcbbranchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbranchidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbranchidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoperation;
    private controls.IntTextField itfcontactno;
    private controls.IntTextField itfstudentid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<java.lang.Object> jcbbranchid;
    private javax.swing.JLabel jmi_contactno;
    private javax.swing.JLabel jmi_emailid;
    private javax.swing.JLabel jmi_fathername;
    private javax.swing.JLabel jmi_studentid;
    private javax.swing.JLabel jmi_studentname;
    private javax.swing.JTextField jtfemailid;
    private javax.swing.JTextField jtffathername;
    private javax.swing.JTextField jtfstudentname;
    // End of variables declaration//GEN-END:variables
}
