/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screens;

import javax.swing.ImageIcon;
import model.dao.DataConnection;
import utility.ErrorHandler;
import static utility.Operations.setApplicationIcon;
import static utility.Operations.openInternalFrame;

/**
 *
 * @author HP
 */
public class AdminMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainScreen
     */
    public AdminMainScreen() {
       
        initComponents();
        setApplicationIcon(this);
        setSize(850,550);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backDesktopPane2 = new controls.BackDesktopPane();
        admin_menu_bar = new javax.swing.JMenuBar();
        menu_bookinfo = new javax.swing.JMenu();
        jmi_add_bookinfo = new javax.swing.JMenuItem();
        viewBooks = new javax.swing.JMenuItem();
        menu_studentinfo = new javax.swing.JMenu();
        jmi_addstudentinfo = new javax.swing.JMenuItem();
        jmi_viewstudentinfo = new javax.swing.JMenuItem();
        jmi_branchinfo = new javax.swing.JMenu();
        jmi_addbranchinfo = new javax.swing.JMenuItem();
        jmi_viewbranchinfo = new javax.swing.JMenuItem();
        jmi_issuedetails = new javax.swing.JMenu();
        jmi_addissuedetails = new javax.swing.JMenuItem();
        jmi_viewissuedetails = new javax.swing.JMenuItem();
        jmi_finedetails = new javax.swing.JMenu();
        jmi_addfinedetails = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().add(backDesktopPane2, java.awt.BorderLayout.CENTER);

        admin_menu_bar.setBackground(new java.awt.Color(153, 153, 255));
        admin_menu_bar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        menu_bookinfo.setBackground(new java.awt.Color(153, 153, 153));
        menu_bookinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11.PNG"))); // NOI18N
        menu_bookinfo.setText("bookinfo");
        menu_bookinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jmi_add_bookinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_add_bookinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jmi_add_bookinfo.setText("add bookinfo");
        jmi_add_bookinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_add_bookinfoActionPerformed(evt);
            }
        });
        menu_bookinfo.add(jmi_add_bookinfo);

        viewBooks.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        viewBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        viewBooks.setText("View Book Details");
        viewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksActionPerformed(evt);
            }
        });
        menu_bookinfo.add(viewBooks);

        admin_menu_bar.add(menu_bookinfo);

        menu_studentinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/14.PNG"))); // NOI18N
        menu_studentinfo.setText("studentinfo");
        menu_studentinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jmi_addstudentinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_addstudentinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jmi_addstudentinfo.setText("add new studentinfo");
        jmi_addstudentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_addstudentinfoActionPerformed(evt);
            }
        });
        menu_studentinfo.add(jmi_addstudentinfo);

        jmi_viewstudentinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_viewstudentinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jmi_viewstudentinfo.setText("view studentinfo");
        jmi_viewstudentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_viewstudentinfoActionPerformed(evt);
            }
        });
        menu_studentinfo.add(jmi_viewstudentinfo);

        admin_menu_bar.add(menu_studentinfo);

        jmi_branchinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/15.PNG"))); // NOI18N
        jmi_branchinfo.setText("branchinfo");
        jmi_branchinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jmi_addbranchinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_addbranchinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jmi_addbranchinfo.setText("add new branchinfo");
        jmi_addbranchinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_addbranchinfoActionPerformed(evt);
            }
        });
        jmi_branchinfo.add(jmi_addbranchinfo);

        jmi_viewbranchinfo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_viewbranchinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jmi_viewbranchinfo.setText("View Branchinfo");
        jmi_viewbranchinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_viewbranchinfoActionPerformed(evt);
            }
        });
        jmi_branchinfo.add(jmi_viewbranchinfo);

        admin_menu_bar.add(jmi_branchinfo);

        jmi_issuedetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16.PNG"))); // NOI18N
        jmi_issuedetails.setText("IssueDetails");
        jmi_issuedetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jmi_addissuedetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_addissuedetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jmi_addissuedetails.setText("Add IssueDetails");
        jmi_addissuedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_addissuedetailsActionPerformed(evt);
            }
        });
        jmi_issuedetails.add(jmi_addissuedetails);

        jmi_viewissuedetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_viewissuedetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jmi_viewissuedetails.setText("view issue details");
        jmi_viewissuedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_viewissuedetailsActionPerformed(evt);
            }
        });
        jmi_issuedetails.add(jmi_viewissuedetails);

        admin_menu_bar.add(jmi_issuedetails);

        jmi_finedetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/17.PNG"))); // NOI18N
        jmi_finedetails.setText("FineDetails");
        jmi_finedetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jmi_addfinedetails.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jmi_addfinedetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jmi_addfinedetails.setText("view fine details");
        jmi_addfinedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_addfinedetailsActionPerformed(evt);
            }
        });
        jmi_finedetails.add(jmi_addfinedetails);

        admin_menu_bar.add(jmi_finedetails);

        setJMenuBar(admin_menu_bar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_add_bookinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_add_bookinfoActionPerformed
       AddBookinfo abi=new AddBookinfo();
       backDesktopPane2.add(abi);
       abi.setVisible(true);
    }//GEN-LAST:event_jmi_add_bookinfoActionPerformed

    private void jmi_addstudentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_addstudentinfoActionPerformed
       AddStudentInfo asi=new AddStudentInfo();
       backDesktopPane2.add(asi);
       asi.setVisible(true);
    }//GEN-LAST:event_jmi_addstudentinfoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
            DataConnection.closeConnection();
        }catch(Exception ex){
            ErrorHandler.showErrorStack(ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jmi_addbranchinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_addbranchinfoActionPerformed
        AddBranchInfo abi=new AddBranchInfo();
        backDesktopPane2.add(abi);
        abi.setVisible(true);
    }//GEN-LAST:event_jmi_addbranchinfoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void viewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksActionPerformed
        openInternalFrame(backDesktopPane2,new ViewBookDetails());
    }//GEN-LAST:event_viewBooksActionPerformed

    private void jmi_viewbranchinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_viewbranchinfoActionPerformed
            openInternalFrame(backDesktopPane2,new ViewBranchinfo());
    }//GEN-LAST:event_jmi_viewbranchinfoActionPerformed

    private void jmi_viewstudentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_viewstudentinfoActionPerformed
         openInternalFrame(backDesktopPane2,new ViewStudentinfo());
    }//GEN-LAST:event_jmi_viewstudentinfoActionPerformed

    private void jmi_addissuedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_addissuedetailsActionPerformed
       openInternalFrame(backDesktopPane2,new AddIssueDetails());
    }//GEN-LAST:event_jmi_addissuedetailsActionPerformed

    private void jmi_viewissuedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_viewissuedetailsActionPerformed
        openInternalFrame(backDesktopPane2,new ViewIssueDetails());
    }//GEN-LAST:event_jmi_viewissuedetailsActionPerformed

    private void jmi_addfinedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_addfinedetailsActionPerformed
        openInternalFrame(backDesktopPane2,new AddFinedetails());
    }//GEN-LAST:event_jmi_addfinedetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar admin_menu_bar;
    private controls.BackDesktopPane backDesktopPane2;
    private javax.swing.JMenuItem jmi_add_bookinfo;
    private javax.swing.JMenuItem jmi_addbranchinfo;
    private javax.swing.JMenuItem jmi_addfinedetails;
    private javax.swing.JMenuItem jmi_addissuedetails;
    private javax.swing.JMenuItem jmi_addstudentinfo;
    private javax.swing.JMenu jmi_branchinfo;
    private javax.swing.JMenu jmi_finedetails;
    private javax.swing.JMenu jmi_issuedetails;
    private javax.swing.JMenuItem jmi_viewbranchinfo;
    private javax.swing.JMenuItem jmi_viewissuedetails;
    private javax.swing.JMenuItem jmi_viewstudentinfo;
    private javax.swing.JMenu menu_bookinfo;
    private javax.swing.JMenu menu_studentinfo;
    private javax.swing.JMenuItem viewBooks;
    // End of variables declaration//GEN-END:variables
}
